blank_issues_enabled: false
contact_links:
  - name: Ideas
    url: https://github.com/rpothin/Power-Platform-Notebooks/discussions/categories/ideas
    about: Please suggest ideas to improve this repository here.
  - name: Questions
    url: https://github.com/rpothin/Power-Platform-Notebooks/discussions/categories/q-a
    about: Please ask and answer questions here.